import { ref, onMounted } from 'vue'

const CITAZIONI_LOCALI = [
    
  // Fallback locale di citazioni italiane motivazionali
  { quote: "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.", author: "Robert Collier" },
  { quote: "La qualità non è mai un caso; è sempre il risultato di uno sforzo intelligente.", author: "John Ruskin" },
  { quote: "L'eccellenza non è un atto, ma un'abitudine.", author: "Aristotele" },
  { quote: "Il modo migliore per predire il futuro è crearlo.", author: "Peter Drucker" },
  { quote: "Non conta quante volte cadi, ma quante volte ti rialzi.", author: "Vince Lombardi" },
  { quote: "La disciplina è il ponte tra gli obiettivi e i risultati.", author: "Jim Rohn" },
  { quote: "Il successo non è definitivo, il fallimento non è fatale: ciò che conta è il coraggio di andare avanti.", author: "Winston Churchill" },
  { quote: "La vera misura di un uomo non è come si comporta nei momenti di comfort, ma come resiste nei tempi di sfida.", author: "Martin Luther King Jr." },
  { quote: "Non aspettare l'opportunità. Creala.", author: "George Bernard Shaw" },
  { quote: "Il talento vince le partite, ma il lavoro di squadra vince i campionati.", author: "Michael Jordan" },
  { quote: "La perfezione non è raggiungibile, ma inseguendola possiamo raggiungere l'eccellenza.", author: "Vince Lombardi" },
  { quote: "Il segreto per andare avanti è iniziare.", author: "Mark Twain" },
  { quote: "Tutto quello che hai sempre voluto è dall'altra parte della paura.", author: "George Addair" },
  { quote: "La differenza tra chi ha successo e chi non ce l'ha non è la mancanza di forza, ma la mancanza di volontà.", author: "Vince Lombardi" },
  { quote: "Non si può tornare indietro e cambiare l'inizio, ma si può iniziare da dove si è e cambiare il finale.", author: "C.S. Lewis" },
  { quote: "L'unico modo per fare un ottimo lavoro è amare quello che fai.", author: "Steve Jobs" },
  { quote: "Credere di farcela è già metà dell'opera.", author: "Theodore Roosevelt" },
  { quote: "I piccoli passi in avanti ogni giorno si sommano in grandi risultati.", author: "Zig Ziglar" },
  { quote: "Il fallimento è semplicemente l'opportunità di ricominciare, questa volta in modo più intelligente.", author: "Henry Ford" },
  { quote: "La motivazione ti porta a iniziare. L'abitudine ti fa continuare.", author: "Jim Ryun" },
  { quote: "Non serve essere grandi per iniziare, ma bisogna iniziare per diventare grandi.", author: "Zig Ziglar" },
  { quote: "Il duro lavoro batte il talento quando il talento non lavora duro.", author: "Tim Notke" },
  { quote: "La chiave del successo è concentrarsi sugli obiettivi, non sugli ostacoli.", author: "Anonimo" },
  { quote: "Ciò che non giova all'alveare non giova neppure all'ape.", author: "Marco Aurelio" },
  { quote: "Il vero viaggio di scoperta non consiste nel cercare nuove terre, ma nell'avere nuovi occhi.", author: "Marcel Proust" },
  { quote: "La vita è per il 10% cosa ti accade e per il 90% come reagisci.", author: "Charles R. Swindoll" },
  { quote: "Non contare i giorni, fai in modo che i giorni contino.", author: "Muhammad Ali" },
  { quote: "La pazienza è amara, ma il suo frutto è dolce.", author: "Aristotele" },
  { quote: "Il momento migliore per piantare un albero era vent'anni fa. Il secondo momento migliore è adesso.", author: "Proverbio cinese" },
  { quote: "Chi cammina da solo può arrivare più veloce, chi cammina in compagnia arriva più lontano.", author: "Proverbio africano" },

  // ── SUCCESSO E RISULTATI (100 citazioni) ──────────────────────────────────
  { quote: "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.", author: "Robert Collier" },
  { quote: "Il modo migliore per predire il futuro è crearlo.", author: "Peter Drucker" },
  { quote: "Il successo non è definitivo, il fallimento non è fatale: ciò che conta è il coraggio di andare avanti.", author: "Winston Churchill" },
  { quote: "L'unico modo per fare un ottimo lavoro è amare quello che fai.", author: "Steve Jobs" },
  { quote: "Credere di farcela è già metà dell'opera.", author: "Theodore Roosevelt" },
  { quote: "Il fallimento è semplicemente l'opportunità di ricominciare, questa volta in modo più intelligente.", author: "Henry Ford" },
  { quote: "Non serve essere grandi per iniziare, ma bisogna iniziare per diventare grandi.", author: "Zig Ziglar" },
  { quote: "La chiave del successo è concentrarsi sugli obiettivi, non sugli ostacoli.", author: "Anonimo" },
  { quote: "Il successo non è la chiave della felicità. La felicità è la chiave del successo.", author: "Albert Schweitzer" },
  { quote: "Non aspettare l'opportunità. Creala.", author: "George Bernard Shaw" },
  { quote: "Il successo è camminare di fallimento in fallimento senza perdere l'entusiasmo.", author: "Winston Churchill" },
  { quote: "Non conta da dove parti, conta dove vuoi arrivare.", author: "Anonimo" },
  { quote: "Il successo è fare ciò che vuoi, quando vuoi, dove vuoi, con chi vuoi, quanto vuoi.", author: "Tony Robbins" },
  { quote: "Ogni grande successo è sempre frutto di molti piccoli successi.", author: "Anonimo" },
  { quote: "Il successo non viene per caso, viene per scelta.", author: "Stephen Covey" },
  { quote: "Più duro lavoro, più fortuna ho.", author: "Thomas Jefferson" },
  { quote: "Il prezzo del successo è duro lavoro, dedizione e determinazione.", author: "Vince Lombardi" },
  { quote: "Il successo è la pace della mente, che è un risultato diretto dell'autostima.", author: "John Wooden" },
  { quote: "Non misurare mai l'altezza di una montagna finché non hai raggiunto la vetta.", author: "Dag Hammarskjöld" },
  { quote: "Il successo è ottenere ciò che vuoi. La felicità è volere ciò che ottieni.", author: "Dale Carnegie" },
  { quote: "Un obiettivo senza un piano è solo un desiderio.", author: "Antoine de Saint-Exupéry" },
  { quote: "Il successo consiste nell'andare di fallimento in fallimento senza perdita di entusiasmo.", author: "Winston Churchill" },
  { quote: "La strada per il successo è sempre in costruzione.", author: "Lily Tomlin" },
  { quote: "Il successo non è un luogo, ma un viaggio.", author: "Zig Ziglar" },
  { quote: "Fai della tua vita un capolavoro.", author: "Leonardo da Vinci" },
  { quote: "Il successo è l'abilità di passare da un fallimento all'altro senza perdere l'entusiasmo.", author: "Winston Churchill" },
  { quote: "Non contare i giorni, fai in modo che i giorni contino.", author: "Muhammad Ali" },
  { quote: "Il successo è una conseguenza, non un obiettivo.", author: "Gustave Flaubert" },
  { quote: "Trasforma le tue ferite in saggezza.", author: "Oprah Winfrey" },
  { quote: "Il vero successo è fare ciò che ami e amare ciò che fai.", author: "Anonimo" },
  { quote: "Il successo non è mai posseduto, è solo affittato, e l'affitto è dovuto ogni giorno.", author: "Rory Vaden" },
  { quote: "I vincitori non sono persone che non falliscono mai, ma persone che non si arrendono mai.", author: "Anonimo" },
  { quote: "Il successo richiede un singolo obiettivo e una dedizione totale.", author: "Chuck Norris" },
  { quote: "Nulla può fermare l'uomo con il giusto atteggiamento mentale.", author: "Thomas Jefferson" },
  { quote: "Il successo non è quanto in alto sali, ma quante persone porti con te.", author: "Will Rose" },
  { quote: "Il segreto del successo è fare le cose comuni in modo non comune.", author: "John D. Rockefeller" },
  { quote: "Il successo non è mai un caso. È sempre il risultato di alta intenzione, impegno sincero e esecuzione intelligente.", author: "Aristotele" },
  { quote: "Sogna in grande e osa fallire.", author: "Norman Vaughan" },
  { quote: "Il successo è dove la preparazione e l'opportunità si incontrano.", author: "Bobby Unser" },
  { quote: "Non desiderare che fosse più facile, desideri essere migliore.", author: "Jim Rohn" },
  { quote: "Il successo arriva a coloro che sono troppo occupati a cercarlo.", author: "Henry David Thoreau" },
  { quote: "Le persone di successo fanno ciò che le persone senza successo non vogliono fare.", author: "Jeff Olson" },
  { quote: "Il successo è la somma di piccoli sforzi, ripetuti giorno dopo giorno.", author: "Robert Collier" },
  { quote: "Non si tratta di essere il migliore. Si tratta di essere migliore di quanto tu fossi ieri.", author: "Anonimo" },
  { quote: "Il successo non è mai stato un incidente.", author: "Zig Ziglar" },
  { quote: "Credi di poterlo fare e sei già a metà strada.", author: "Theodore Roosevelt" },
  { quote: "Il successo di solito arriva a coloro che sono troppo occupati per cercarlo.", author: "Henry David Thoreau" },
  { quote: "La motivazione è ciò che ti fa iniziare. L'abitudine è ciò che ti fa andare avanti.", author: "Jim Ryun" },
  { quote: "Non è mai troppo tardi per essere ciò che avresti potuto essere.", author: "George Eliot" },
  { quote: "Il successo non è la fine, il fallimento non è fatale: è il coraggio di continuare che conta.", author: "Winston Churchill" },
  { quote: "Il miglior modo per prevedere il futuro è inventarlo.", author: "Alan Kay" },
  { quote: "Inizia dove sei. Usa ciò che hai. Fai ciò che puoi.", author: "Arthur Ashe" },
  { quote: "Il successo non è mai definitivo, il fallimento non è mai fatale.", author: "Mike Ditka" },
  { quote: "La differenza tra il possibile e l'impossibile sta nella determinazione di una persona.", author: "Tommy Lasorda" },
  { quote: "Il successo è fare ciò che ami e farlo al meglio delle tue capacità.", author: "Anonimo" },
  { quote: "Non aspettare. Il tempo non sarà mai giusto.", author: "Napoleon Hill" },
  { quote: "Il successo è la capacità di andare da un fallimento all'altro senza perdere entusiasmo.", author: "Winston Churchill" },
  { quote: "Se puoi sognarlo, puoi farlo.", author: "Walt Disney" },
  { quote: "Il successo è ottenere ciò per cui hai lavorato.", author: "Anonimo" },
  { quote: "Non ti arrendere mai, perché è proprio quel momento in cui le cose cambieranno.", author: "Anonimo" },
  { quote: "Il successo non è un luogo a cui arrivare, ma il modo in cui viaggi.", author: "Anonimo" },
  { quote: "Fai quello che puoi con quello che hai, dove sei.", author: "Theodore Roosevelt" },
  { quote: "Il successo è preparazione che incontra l'opportunità.", author: "Zig Ziglar" },
  { quote: "Non puoi scalare la scala del successo con le mani in tasca.", author: "Arnold Schwarzenegger" },
  { quote: "Il successo non è mai posseduto, va conquistato ogni giorno.", author: "Anonimo" },
  { quote: "La strada per il successo è costellata di molti attraenti parcheggi.", author: "Will Rogers" },
  { quote: "Il successo è la realizzazione progressiva di un obiettivo degno.", author: "Earl Nightingale" },
  { quote: "Non è importante quante volte cadi, ma quante volte ti rialzi.", author: "Vince Lombardi" },
  { quote: "Il successo non è per i pigri.", author: "Anonimo" },
  { quote: "Ogni fallimento è un passo verso il successo.", author: "William Whewell" },
  { quote: "Il successo è una conseguenza naturale del costante impegno per l'eccellenza.", author: "Anonimo" },
  { quote: "Non smettere mai di imparare, perché la vita non smette mai di insegnare.", author: "Anonimo" },
  { quote: "Il successo richiede persistenza, la capacità di non arrendersi di fronte al fallimento.", author: "Anonimo" },
  { quote: "L'unica cosa impossibile è quella che non provi.", author: "Anonimo" },
  { quote: "Il successo è fare ciò che è difficile e farlo sembrare facile.", author: "Anonimo" },
  { quote: "Non conta quanto lentamente vai, purché non ti fermi.", author: "Confucio" },
  { quote: "Il successo è la migliore vendetta.", author: "Anonimo" },
  { quote: "Sii così bravo che non possano ignorarti.", author: "Steve Martin" },
  { quote: "Il successo non arriva ai sognatori, arriva a coloro che agiscono.", author: "Anonimo" },
  { quote: "Non accontentarti della mediocrità quando puoi raggiungere l'eccellenza.", author: "Anonimo" },
  { quote: "Il successo è ciò che accade quando la preparazione incontra l'opportunità.", author: "Seneca" },
  { quote: "La determinazione è la chiave del successo.", author: "Anonimo" },
  { quote: "Il successo è un viaggio, non una destinazione.", author: "Ben Sweetland" },
  { quote: "Non smettere mai di provare solo perché qualcosa sembra difficile.", author: "Anonimo" },
  { quote: "Il successo è costruito su fallimenti tanto quanto su vittorie.", author: "Anonimo" },
  { quote: "La tua unica limitazione è quella che hai nella tua mente.", author: "Napoleon Hill" },
  { quote: "Il successo è nella mente prima di essere nelle mani.", author: "Anonimo" },
  { quote: "Non permettere a ciò che non puoi fare di interferire con ciò che puoi fare.", author: "John Wooden" },
  { quote: "Il successo è il risultato della preparazione, del duro lavoro e dell'imparare dai fallimenti.", author: "Colin Powell" },
  { quote: "Tutto ciò che la mente può concepire e credere, può realizzare.", author: "Napoleon Hill" },
  { quote: "Il successo non ti trova. Devi andare a cercarlo.", author: "Anonimo" },
  { quote: "La differenza tra il possibile e l'impossibile sta nella volontà di una persona.", author: "Louis Pasteur" },
  { quote: "Il successo richiede sacrificio.", author: "Anonimo" },
  { quote: "Non aspettare il momento perfetto, prendi il momento e rendilo perfetto.", author: "Anonimo" },
  { quote: "Il successo è dolce, ma il viaggio per raggiungerlo è ancora più dolce.", author: "Anonimo" },
  { quote: "Sei più vicino al successo di quanto pensi.", author: "Anonimo" },
  { quote: "Il successo richiede coraggio, non perfezione.", author: "Anonimo" },
  { quote: "Non lasciare che il tuo passato detti il tuo futuro.", author: "Anonimo" },

  // ── LAVORO E PROFESSIONALITÀ (100 citazioni) ──────────────────────────────
  { quote: "La qualità non è mai un caso; è sempre il risultato di uno sforzo intelligente.", author: "John Ruskin" },
  { quote: "La disciplina è il ponte tra gli obiettivi e i risultati.", author: "Jim Rohn" },
  { quote: "Il duro lavoro batte il talento quando il talento non lavora duro.", author: "Tim Notke" },
  { quote: "L'opportunità è mancata dalla maggior parte delle persone perché è vestita in tuta e assomiglia al lavoro.", author: "Thomas Edison" },
  { quote: "Fai del tuo lavoro una cosa bellissima.", author: "Michelangelo" },
  { quote: "Il lavoro di oggi è il successo di domani.", author: "Anonimo" },
  { quote: "Il lavoro ben fatto è sempre ricompensato.", author: "Anonimo" },
  { quote: "Non c'è sostituto per il duro lavoro.", author: "Thomas Edison" },
  { quote: "Il genio è 1% ispirazione e 99% traspirazione.", author: "Thomas Edison" },
  { quote: "Il lavoro allontana da noi tre grandi mali: la noia, il vizio e il bisogno.", author: "Voltaire" },
  { quote: "Chi lavora con le sue mani è un lavoratore. Chi lavora con le sue mani e la sua testa è un artigiano. Chi lavora con le sue mani, la sua testa e il suo cuore è un artista.", author: "San Francesco d'Assisi" },
  { quote: "Il lavoro nobilita l'uomo.", author: "Proverbio" },
  { quote: "Scegli un lavoro che ami, e non dovrai lavorare neppure un giorno in vita tua.", author: "Confucio" },
  { quote: "Il miglior modo per apprezzare il tuo lavoro è immaginare te stesso senza di esso.", author: "Oscar Wilde" },
  { quote: "Non aspettare che le cose accadano. Fai in modo che accadano.", author: "Anonimo" },
  { quote: "Il lavoro duro è il prezzo del successo.", author: "Anonimo" },
  { quote: "La perfezione non è raggiungibile, ma se inseguiamo la perfezione possiamo raggiungere l'eccellenza.", author: "Vince Lombardi" },
  { quote: "Il tuo lavoro occuperà gran parte della tua vita, l'unico modo per essere veramente soddisfatti è fare ciò che credi sia un lavoro eccellente.", author: "Steve Jobs" },
  { quote: "Il lavoro è l'unico capitale che non può essere espropriato.", author: "Anonimo" },
  { quote: "Lavora come se non avessi bisogno di soldi, ama come se non fossi mai stato ferito, balla come se nessuno ti stesse guardando.", author: "Mark Twain" },
  { quote: "Il lavoro è il rifugio di coloro che non hanno niente di meglio da fare.", author: "Oscar Wilde" },
  { quote: "Nessun lavoro è umiliante se fatto con dignità.", author: "Anonimo" },
  { quote: "Il lavoro ci salva dalla tre grandi mali: la noia, il vizio e la necessità.", author: "Voltaire" },
  { quote: "La produttività non è mai un incidente. È sempre il risultato di un impegno per l'eccellenza, pianificazione intelligente e sforzo concentrato.", author: "Paul J. Meyer" },
  { quote: "Il lavoro ben fatto parla da solo.", author: "Anonimo" },
  { quote: "Non c'è traffico sulla miglio extra.", author: "Roger Staubach" },
  { quote: "Il lavoro duro supera il talento naturale.", author: "Anonimo" },
  { quote: "La differenza tra ordinario e straordinario è quel poco di più.", author: "Jimmy Johnson" },
  { quote: "Il lavoro costante conquista tutti gli ostacoli.", author: "Virgilio" },
  { quote: "La professionalità è sapere come farlo, quando farlo e farlo.", author: "Frank Tyger" },
  { quote: "L'eccellenza è fare una cosa comune in modo non comune.", author: "Booker T. Washington" },
  { quote: "Il lavoro è amore reso visibile.", author: "Khalil Gibran" },
  { quote: "Fai bene ogni lavoro, grande o piccolo. Non c'è niente di troppo piccolo per essere fatto bene.", author: "Anonimo" },
  { quote: "Il vero professionista non sceglie tra far bene e far presto: fa entrambe le cose.", author: "Anonimo" },
  { quote: "La qualità del tuo lavoro riflette la qualità del tuo carattere.", author: "Anonimo" },
  { quote: "Il lavoro etico è il fondamento di ogni grande carriera.", author: "Anonimo" },
  { quote: "La professionalità è consistenza nelle prestazioni.", author: "Anonimo" },
  { quote: "Il lavoro fatto con passione produce risultati eccellenti.", author: "Anonimo" },
  { quote: "La dedizione al lavoro è la madre del successo.", author: "Anonimo" },
  { quote: "Un lavoro ben fatto non ha bisogno di essere lodato, si loda da solo.", author: "Anonimo" },
  { quote: "Il professionista sa che non esistono scorciatoie per l'eccellenza.", author: "Anonimo" },
  { quote: "Il lavoro è il miglior investimento che puoi fare su te stesso.", author: "Anonimo" },
  { quote: "La diligenza è la madre della buona fortuna.", author: "Benjamin Franklin" },
  { quote: "Lavora in silenzio e lascia che il tuo successo faccia rumore.", author: "Anonimo" },
  { quote: "Il lavoro duro è insostituibile.", author: "Anonimo" },
  { quote: "La professionalità non è un titolo, è un comportamento.", author: "Anonimo" },
  { quote: "Il lavoro ben fatto è la migliore pubblicità.", author: "Anonimo" },
  { quote: "L'attenzione ai dettagli separa i professionisti dai dilettanti.", author: "Anonimo" },
  { quote: "Il lavoro di qualità non accade per caso.", author: "Anonimo" },
  { quote: "La coerenza nel lavoro costruisce la reputazione.", author: "Anonimo" },
  { quote: "Il professionista trova soluzioni, l'amatore trova scuse.", author: "Anonimo" },
  { quote: "Il lavoro etico prevale sempre sul talento.", author: "Anonimo" },
  { quote: "La puntualità è la cortesia dei re e il dovere dei professionisti.", author: "Luigi XVIII" },
  { quote: "Il lavoro costante è il segreto di ogni maestria.", author: "Anonimo" },
  { quote: "La professionalità è fare le cose giuste anche quando nessuno guarda.", author: "Anonimo" },
  { quote: "Il lavoro ben pianificato è metà del lavoro fatto.", author: "Anonimo" },
  { quote: "L'eccellenza nel lavoro è un'abitudine, non un atto.", author: "Aristotele" },
  { quote: "Il professionista impara dai propri errori e non li ripete.", author: "Anonimo" },
  { quote: "Il lavoro svolto con integrità non teme confronti.", author: "Anonimo" },
  { quote: "La precisione è il marchio del professionista.", author: "Anonimo" },
  { quote: "Il lavoro ben fatto è fonte di orgoglio personale.", author: "Anonimo" },
  { quote: "La professionalità si misura dalla costanza, non dall'intensità.", author: "Anonimo" },
  { quote: "Il lavoro fatto con cura non ha bisogno di rifacimenti.", author: "Anonimo" },
  { quote: "L'attenzione per il cliente è la base della professionalità.", author: "Anonimo" },
  { quote: "Il lavoro di squadra moltiplica i risultati individuali.", author: "Anonimo" },
  { quote: "La professionalità è rispetto per il proprio lavoro e per quello altrui.", author: "Anonimo" },
  { quote: "Il lavoro metodico produce risultati prevedibili.", author: "Anonimo" },
  { quote: "La competenza si costruisce giorno dopo giorno.", author: "Anonimo" },
  { quote: "Il professionista sa dire 'non lo so' e poi impara.", author: "Anonimo" },
  { quote: "Il lavoro ben organizzato riduce lo stress e aumenta la produttività.", author: "Anonimo" },
  { quote: "La professionalità è la capacità di mantenere la calma sotto pressione.", author: "Anonimo" },
  { quote: "Il lavoro fatto con passione non pesa.", author: "Anonimo" },
  { quote: "L'umiltà professionale è sapere che c'è sempre da migliorare.", author: "Anonimo" },
  { quote: "Il lavoro di precisione richiede tempo e pazienza.", author: "Anonimo" },
  { quote: "La professionalità è saper gestire le priorità.", author: "Anonimo" },
  { quote: "Il lavoro ben documentato facilita la continuità.", author: "Anonimo" },
  { quote: "La responsabilità è il pilastro della professionalità.", author: "Anonimo" },
  { quote: "Il lavoro svolto con etica costruisce fiducia.", author: "Anonimo" },
  { quote: "La professionalità è saper dire di no quando necessario.", author: "Anonimo" },
  { quote: "Il lavoro costante supera l'intelligenza occasionale.", author: "Anonimo" },
  { quote: "La puntualità nelle consegne è rispetto per gli altri.", author: "Anonimo" },
  { quote: "Il lavoro ben comunicato evita malintesi.", author: "Anonimo" },
  { quote: "La professionalità è agire con coerenza tra parole e fatti.", author: "Anonimo" },
  { quote: "Il lavoro collaborativo produce risultati superiori.", author: "Anonimo" },
  { quote: "L'affidabilità è la base della reputazione professionale.", author: "Anonimo" },
  { quote: "Il lavoro svolto con rispetto crea armonia.", author: "Anonimo" },
  { quote: "La professionalità è adattarsi al cambiamento mantenendo gli standard.", author: "Anonimo" },
  { quote: "Il lavoro ben eseguito non richiede giustificazioni.", author: "Anonimo" },
  { quote: "La crescita professionale richiede formazione continua.", author: "Anonimo" },
  { quote: "Il lavoro fatto oggi facilita il domani.", author: "Anonimo" },
  { quote: "La professionalità è saper lavorare in autonomia.", author: "Anonimo" },
  { quote: "Il lavoro ordinato produce menti ordinate.", author: "Anonimo" },
  { quote: "La trasparenza nel lavoro costruisce credibilità.", author: "Anonimo" },
  { quote: "Il professionista cerca feedback per migliorare.", author: "Anonimo" },
  { quote: "Il lavoro ben fatto oggi è il successo di domani.", author: "Anonimo" },
  { quote: "La professionalità è rispettare le scadenze.", author: "Anonimo" },
  { quote: "Il lavoro svolto con integrità resiste al tempo.", author: "Anonimo" },

  // ── TEAMWORK E COLLABORAZIONE (100 citazioni) ──────────────────────────────
  { quote: "Il talento vince le partite, ma il lavoro di squadra vince i campionati.", author: "Michael Jordan" },
  { quote: "Ciò che non giova all'alveare non giova neppure all'ape.", author: "Marco Aurelio" },
  { quote: "Chi cammina da solo può arrivare più veloce, chi cammina in compagnia arriva più lontano.", author: "Proverbio africano" },
  { quote: "Individualmente siamo una goccia. Insieme siamo un oceano.", author: "Ryunosuke Satoro" },
  { quote: "Da soli possiamo fare così poco; insieme possiamo fare così tanto.", author: "Helen Keller" },
  { quote: "Il lavoro di squadra divide i compiti e moltiplica il successo.", author: "Anonimo" },
  { quote: "Nessuno di noi è intelligente quanto tutti noi insieme.", author: "Ken Blanchard" },
  { quote: "Un team è più della somma delle sue parti.", author: "Anonimo" },
  { quote: "Il lavoro di squadra inizia con la fiducia.", author: "Patrick Lencioni" },
  { quote: "Insieme tutti raggiungiamo di più.", author: "Anonimo" },
  { quote: "La collaborazione è la chiave del progresso.", author: "Anonimo" },
  { quote: "Un gruppo diventa squadra quando ogni membro è sicuro abbastanza di sé da lodare gli altri.", author: "Norman Shidle" },
  { quote: "Il lavoro di squadra rende i sogni realtà.", author: "Anonimo" },
  { quote: "I grandi risultati non sono mai il frutto di una sola persona, ma di molte mani e cuori che lavorano insieme.", author: "Anonimo" },
  { quote: "La forza del team è ogni singolo membro. La forza di ogni membro è il team.", author: "Phil Jackson" },
  { quote: "Nessuno può fischiettare una sinfonia. Ci vuole un'intera orchestra per suonarla.", author: "H.E. Luccock" },
  { quote: "Il lavoro di squadra è l'abilità di lavorare insieme verso una visione comune.", author: "Andrew Carnegie" },
  { quote: "Se vuoi andare veloce, vai da solo. Se vuoi andare lontano, vai insieme.", author: "Proverbio africano" },
  { quote: "La collaborazione moltiplica le capacità individuali.", author: "Anonimo" },
  { quote: "Un team non è un gruppo di persone che lavorano insieme. È un gruppo di persone che si fidano l'una dell'altra.", author: "Simon Sinek" },
  { quote: "Il successo del team è il successo di ognuno.", author: "Anonimo" },
  { quote: "La diversità nel team è forza, non debolezza.", author: "Anonimo" },
  { quote: "Insieme possiamo affrontare qualsiasi sfida.", author: "Anonimo" },
  { quote: "Il rispetto reciproco è il fondamento del lavoro di squadra.", author: "Anonimo" },
  { quote: "La comunicazione è il carburante del lavoro di squadra.", author: "Anonimo" },
  { quote: "Un buon team è come una macchina ben oliata.", author: "Anonimo" },
  { quote: "La collaborazione trasforma l'ordinario in straordinario.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, il silenzio dell'ego è importante quanto la voce delle idee.", author: "Anonimo" },
  { quote: "Il team vincente ha un obiettivo comune che è più grande dei singoli obiettivi.", author: "Anonimo" },
  { quote: "La fiducia è il collante che tiene unito un team.", author: "Anonimo" },
  { quote: "Un team forte accoglie le differenze e le trasforma in punti di forza.", author: "Anonimo" },
  { quote: "La collaborazione crea sinergie impossibili da raggiungere da soli.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, l'ascolto è importante quanto il parlare.", author: "Anonimo" },
  { quote: "Il team di successo celebra i risultati insieme e affronta le difficoltà unito.", author: "Anonimo" },
  { quote: "La complementarietà delle competenze rende un team imbattibile.", author: "Anonimo" },
  { quote: "Un team funziona quando tutti remano nella stessa direzione.", author: "Anonimo" },
  { quote: "La collaborazione efficace richiede umiltà e generosità.", author: "Anonimo" },
  { quote: "Nel team, il successo di uno è il successo di tutti.", author: "Anonimo" },
  { quote: "La condivisione delle conoscenze moltiplica il potenziale del team.", author: "Anonimo" },
  { quote: "Un team coeso è più forte della somma delle sue parti.", author: "Anonimo" },
  { quote: "La collaborazione richiede apertura mentale e flessibilità.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, dare supporto è importante quanto riceverlo.", author: "Anonimo" },
  { quote: "Un team eccellente trasforma i problemi in opportunità.", author: "Anonimo" },
  { quote: "La diversità di pensiero arricchisce le decisioni del team.", author: "Anonimo" },
  { quote: "La collaborazione costruisce ponti dove la competizione costruisce muri.", author: "Anonimo" },
  { quote: "Un team motivato non conosce ostacoli insormontabili.", author: "Anonimo" },
  { quote: "La condivisione degli obiettivi crea allineamento nel team.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, la responsabilità è condivisa.", author: "Anonimo" },
  { quote: "Un team resiliente si rafforza nelle difficoltà.", author: "Anonimo" },
  { quote: "La collaborazione efficace richiede chiarezza nei ruoli.", author: "Anonimo" },
  { quote: "Un team sano comunica apertamente e costruttivamente.", author: "Anonimo" },
  { quote: "La fiducia reciproca accelera i risultati del team.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, ogni contributo conta.", author: "Anonimo" },
  { quote: "Un team innovativo accoglie le idee di tutti.", author: "Anonimo" },
  { quote: "La collaborazione richiede pazienza e comprensione.", author: "Anonimo" },
  { quote: "Un team vincente impara dai propri errori.", author: "Anonimo" },
  { quote: "La condivisione delle vittorie rafforza il team.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, l'umiltà è una virtù.", author: "Anonimo" },
  { quote: "Un team efficace pianifica insieme ed esegue insieme.", author: "Anonimo" },
  { quote: "La collaborazione trasforma i limiti individuali in possibilità collettive.", author: "Anonimo" },
  { quote: "Un team coeso sa quando collaborare e quando dare spazio.", author: "Anonimo" },
  { quote: "La diversità nel team porta a soluzioni più creative.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, l'onestà costruisce fiducia.", author: "Anonimo" },
  { quote: "Un team motivato si auto-organizza verso l'obiettivo.", author: "Anonimo" },
  { quote: "La collaborazione richiede equilibrio tra dare e ricevere.", author: "Anonimo" },
  { quote: "Un team resiliente celebra i piccoli progressi.", author: "Anonimo" },
  { quote: "La condivisione delle responsabilità alleggerisce il carico.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, la critica costruttiva è crescita.", author: "Anonimo" },
  { quote: "Un team agile si adatta rapidamente ai cambiamenti.", author: "Anonimo" },
  { quote: "La collaborazione efficace nasce dal rispetto reciproco.", author: "Anonimo" },
  { quote: "Un team eccellente valorizza i punti di forza di ciascuno.", author: "Anonimo" },
  { quote: "La diversità culturale arricchisce la prospettiva del team.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, la trasparenza previene i conflitti.", author: "Anonimo" },
  { quote: "Un team innovativo sperimenta senza paura di sbagliare.", author: "Anonimo" },
  { quote: "La collaborazione richiede ascolto attivo e empatia.", author: "Anonimo" },
  { quote: "Un team coeso sa gestire i disaccordi costruttivamente.", author: "Anonimo" },
  { quote: "La condivisione della visione allinea gli sforzi del team.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, il feedback è un dono.", author: "Anonimo" },
  { quote: "Un team resiliente trasforma le crisi in opportunità di crescita.", author: "Anonimo" },
  { quote: "La collaborazione amplifica i talenti individuali.", author: "Anonimo" },
  { quote: "Un team vincente celebra sia il viaggio che la destinazione.", author: "Anonimo" },
  { quote: "La diversità di competenze crea complementarietà nel team.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, la flessibilità è essenziale.", author: "Anonimo" },
  { quote: "Un team motivato si sostiene nei momenti difficili.", author: "Anonimo" },
  { quote: "La collaborazione efficace richiede coordinamento e sincronizzazione.", author: "Anonimo" },
  { quote: "Un team eccellente sa quando guidare e quando seguire.", author: "Anonimo" },
  { quote: "La condivisione delle best practice eleva il livello del team.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, l'inclusione è forza.", author: "Anonimo" },
  { quote: "Un team agile abbraccia il cambiamento come opportunità.", author: "Anonimo" },
  { quote: "La collaborazione richiede disponibilità ad aiutare e essere aiutati.", author: "Anonimo" },
  { quote: "Un team coeso supera le sfide che sembravano impossibili.", author: "Anonimo" },
  { quote: "La diversità generazionale porta esperienza e innovazione.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, ogni voce merita di essere ascoltata.", author: "Anonimo" },
  { quote: "Un team vincente sa che il fallimento collettivo è apprendimento condiviso.", author: "Anonimo" },
  { quote: "La collaborazione costruisce relazioni che durano oltre il progetto.", author: "Anonimo" },
  { quote: "Un team resiliente trova forza nell'unità.", author: "Anonimo" },
  { quote: "La condivisione degli insegnamenti previene la ripetizione degli errori.", author: "Anonimo" },
  { quote: "Nel lavoro di squadra, la gratitudine rafforza i legami.", author: "Anonimo" },

  // ── APPRENDIMENTO E CRESCITA (100 citazioni) ────────────────────────────────
  { quote: "L'eccellenza non è un atto, ma un'abitudine.", author: "Aristotele" },
  { quote: "Non conta quante volte cadi, ma quante volte ti rialzi.", author: "Vince Lombardi" },
  { quote: "I piccoli passi in avanti ogni giorno si sommano in grandi risultati.", author: "Zig Ziglar" },
  { quote: "La motivazione ti porta a iniziare. L'abitudine ti fa continuare.", author: "Jim Ryun" },
  { quote: "Non si può tornare indietro e cambiare l'inizio, ma si può iniziare da dove si è e cambiare il finale.", author: "C.S. Lewis" },
  { quote: "Il vero viaggio di scoperta non consiste nel cercare nuove terre, ma nell'avere nuovi occhi.", author: "Marcel Proust" },
  { quote: "L'apprendimento non si esaurisce mai. È il fuoco che non si spegne mai.", author: "Anonimo" },
  { quote: "Chi smette di imparare è vecchio, che abbia venti o ottanta anni.", author: "Henry Ford" },
  { quote: "L'educazione è l'arma più potente che si possa usare per cambiare il mondo.", author: "Nelson Mandela" },
  { quote: "Impara come se dovessi vivere per sempre.", author: "Mahatma Gandhi" },
  { quote: "La conoscenza è potere.", author: "Francis Bacon" },
  { quote: "Chi non sa nulla, non dubita di nulla.", author: "Proverbio" },
  { quote: "L'apprendimento è un tesoro che seguirà il suo proprietario ovunque.", author: "Proverbio cinese" },
  { quote: "L'istruzione è il passaporto per il futuro.", author: "Malcolm X" },
  { quote: "La mente che si apre a una nuova idea non torna mai alla dimensione precedente.", author: "Albert Einstein" },
  { quote: "Impara dai ieri, vivi per oggi, spera per domani.", author: "Albert Einstein" },
  { quote: "La formazione è costosa, l'ignoranza lo è ancora di più.", author: "Anonimo" },
  { quote: "Chi non legge, a 70 anni avrà vissuto una sola vita: la propria. Chi legge avrà vissuto 5000 anni.", author: "Umberto Eco" },
  { quote: "L'apprendimento è esperienza, tutto il resto è solo informazione.", author: "Albert Einstein" },
  { quote: "Il segreto del cambiamento è concentrare tutta la tua energia non nel combattere il vecchio, ma nel costruire il nuovo.", author: "Socrate" },
  { quote: "La curiosità è il motore dell'apprendimento.", author: "Anonimo" },
  { quote: "Ogni esperto è stato una volta un principiante.", author: "Anonimo" },
  { quote: "Il fallimento è semplicemente l'opportunità di ricominciare in modo più intelligente.", author: "Henry Ford" },
  { quote: "L'apprendimento continuo è il minimo necessario per avere successo in qualsiasi campo.", author: "Brian Tracy" },
  { quote: "La crescita inizia quando usciamo dalla nostra zona di comfort.", author: "Anonimo" },
  { quote: "Chi ha pazienza può ottenere ciò che vuole.", author: "Benjamin Franklin" },
  { quote: "L'apprendimento non è mai un caso, è sempre il risultato di un alto ideale, impegno sincero e esecuzione intelligente.", author: "William Arthur Ward" },
  { quote: "La vita è un processo di apprendimento continuo.", author: "Anonimo" },
  { quote: "Sbagliare è umano, ma imparare dall'errore è divino.", author: "Anonimo" },
  { quote: "La crescita personale è un processo, non una destinazione.", author: "Anonimo" },
  { quote: "Ciò che sappiamo è una goccia, ciò che non sappiamo è un oceano.", author: "Isaac Newton" },
  { quote: "L'apprendimento è il solo passatempo che non stanca mai.", author: "Anonimo" },
  { quote: "Non è mai troppo tardi per imparare.", author: "Anonimo" },
  { quote: "La conoscenza che non cresce ogni giorno diminuisce ogni giorno.", author: "Proverbio cinese" },
  { quote: "Investi in te stesso, è il miglior investimento che puoi fare.", author: "Warren Buffett" },
  { quote: "L'apprendimento è un dono, anche quando il dolore è il tuo insegnante.", author: "Anonimo" },
  { quote: "La pratica rende perfetti.", author: "Proverbio" },
  { quote: "Chi insegna impara due volte.", author: "Joseph Joubert" },
  { quote: "L'apprendimento senza pensiero è fatica sprecata.", author: "Confucio" },
  { quote: "La crescita richiede il coraggio di lasciare andare il familiare.", author: "Anonimo" },
  { quote: "Ogni giorno è una scuola, ogni persona è un insegnante.", author: "Anonimo" },
  { quote: "L'apprendimento è il principio della ricchezza.", author: "Jim Rohn" },
  { quote: "La vera saggezza è sapere di non sapere.", author: "Socrate" },
  { quote: "L'istruzione è ciò che rimane dopo che uno ha dimenticato tutto quello che ha imparato a scuola.", author: "Albert Einstein" },
  { quote: "Chi domanda può essere stupido per cinque minuti. Chi non domanda è stupido per sempre.", author: "Proverbio cinese" },
  { quote: "L'apprendimento è come remare contro corrente: se smetti, torni indietro.", author: "Edward Benjamin Britten" },
  { quote: "La crescita personale è dolorosa, ma nulla è doloroso quanto rimanere bloccati dove non appartieni.", author: "Anonimo" },
  { quote: "Impara le regole come un professionista, così potrai infrangerle come un artista.", author: "Pablo Picasso" },
  { quote: "L'apprendimento è la bussola che guida il nostro viaggio.", author: "Anonimo" },
  { quote: "Chi non legge non ha alcun vantaggio su chi non sa leggere.", author: "Mark Twain" },
  { quote: "La crescita avviene quando usciamo dalla nostra zona di comfort.", author: "Anonimo" },
  { quote: "L'apprendimento veloce è il vantaggio competitivo definitivo.", author: "Jack Welch" },
  { quote: "La curiosità è l'inizio della saggezza.", author: "Anonimo" },
  { quote: "Chi impara da giovane, è come scrivere sulla pietra.", author: "Proverbio" },
  { quote: "L'apprendimento è l'unico processo naturale anti-invecchiamento.", author: "Anonimo" },
  { quote: "La formazione è investimento, non una spesa.", author: "Anonimo" },
  { quote: "Chi studia senza riflettere è perduto, chi riflette senza studiare è in pericolo.", author: "Confucio" },
  { quote: "L'apprendimento è il primo passo verso la libertà.", author: "Anonimo" },
  { quote: "La mente è come un paracadute: funziona solo quando è aperta.", author: "Frank Zappa" },
  { quote: "Chi non fa errori, non fa niente.", author: "Proverbio" },
  { quote: "L'apprendimento è un viaggio, non una destinazione.", author: "Anonimo" },
  { quote: "La crescita richiede l'abbandono di vecchie abitudini.", author: "Anonimo" },
  { quote: "Chi sa, fa. Chi non sa, insegna. Chi non sa insegnare, insegna a insegnare.", author: "Anonimo" },
  { quote: "L'apprendimento è l'unica cosa di cui la mente non si stanca mai.", author: "Leonardo da Vinci" },
  { quote: "La conoscenza senza azione è inutile.", author: "Anonimo" },
  { quote: "Chi legge viaggia, chi non legge si ferma.", author: "Anonimo" },
  { quote: "L'apprendimento permanente è il nuovo imperativo professionale.", author: "Anonimo" },
  { quote: "La crescita personale richiede auto-riflessione.", author: "Anonimo" },
  { quote: "Chi smette di essere migliore, smette di essere buono.", author: "Oliver Cromwell" },
  { quote: "L'apprendimento è la chiave che apre tutte le porte.", author: "Anonimo" },
  { quote: "La formazione formale ti farà vivere, l'auto-formazione ti farà guadagnare.", author: "Jim Rohn" },
  { quote: "Chi non progredisce, regredisce.", author: "Proverbio" },
  { quote: "L'apprendimento esperienziale è il più potente.", author: "Anonimo" },
  { quote: "La crescita inizia alla fine della tua zona di comfort.", author: "Tony Robbins" },
  { quote: "Chi non cambia mai idea, non avrà mai nuove idee.", author: "Anonimo" },
  { quote: "L'apprendimento è investimento sul futuro.", author: "Anonimo" },
  { quote: "La conoscenza condivisa è conoscenza moltiplicata.", author: "Anonimo" },
  { quote: "Chi pensa di sapere tutto, ha smesso di imparare.", author: "Anonimo" },
  { quote: "L'apprendimento attivo supera l'ascolto passivo.", author: "Anonimo" },
  { quote: "La crescita richiede sfide costanti.", author: "Anonimo" },
  { quote: "Chi non si forma, si ferma.", author: "Anonimo" },
  { quote: "L'apprendimento collaborativo amplifica i risultati.", author: "Anonimo" },
  { quote: "La conoscenza è l'unico bene che aumenta quando viene condiviso.", author: "Anonimo" },
  { quote: "Chi non sperimenta, non impara.", author: "Anonimo" },
  { quote: "L'apprendimento è la moneta del futuro.", author: "Anonimo" },
  { quote: "La crescita personale è responsabilità personale.", author: "Anonimo" },
  { quote: "Chi non cerca, non trova.", author: "Proverbio" },
  { quote: "L'apprendimento digitale democratizza l'accesso alla conoscenza.", author: "Anonimo" },
  { quote: "La formazione continua è il nuovo standard professionale.", author: "Anonimo" },
  { quote: "Chi non si aggiorna, si supera.", author: "Anonimo" },
  { quote: "L'apprendimento peer-to-peer è molto efficace.", author: "Anonimo" },
  { quote: "La crescita richiede umiltà nell'ammettere di non sapere.", author: "Anonimo" },
  { quote: "Chi non pratica, dimentica.", author: "Proverbio" },
  { quote: "L'apprendimento micro è il trend del futuro.", author: "Anonimo" },
  { quote: "La conoscenza applicata è potere reale.", author: "Anonimo" },
  { quote: "Chi non si adatta, si estingue.", author: "Charles Darwin" },
  { quote: "L'apprendimento basato su progetti consolida le competenze.", author: "Anonimo" },
  { quote: "La crescita professionale richiede riflessione sulle esperienze.", author: "Anonimo" },

  // ── LEADERSHIP E RESPONSABILITÀ (100 citazioni) ────────────────────────────
  { quote: "La vera misura di un uomo non è come si comporta nei momenti di comfort, ma come resiste nei tempi di sfida.", author: "Martin Luther King Jr." },
  { quote: "La perfezione non è raggiungibile, ma inseguendola possiamo raggiungere l'eccellenza.", author: "Vince Lombardi" },
  { quote: "La differenza tra chi ha successo e chi non ce l'ha non è la mancanza di forza, ma la mancanza di volontà.", author: "Vince Lombardi" },
  { quote: "Un leader è colui che conosce la strada, percorre la strada e mostra la strada.", author: "John C. Maxwell" },
  { quote: "La leadership è azione, non posizione.", author: "Donald McGannon" },
  { quote: "Un vero leader non crea seguaci, crea altri leader.", author: "Anonimo" },
  { quote: "Il compito di un leader è portare le persone da dove sono a dove non sono mai state.", author: "Henry Kissinger" },
  { quote: "La leadership è influenza, niente di più, niente di meno.", author: "John C. Maxwell" },
  { quote: "Un leader pensa e parla di soluzioni. Un seguace pensa e parla di problemi.", author: "Brian Tracy" },
  { quote: "La leadership è la capacità di tradurre la visione in realtà.", author: "Warren Bennis" },
  { quote: "Il miglior leader è quello la cui esistenza è appena nota, quando il lavoro è fatto, il suo scopo raggiunto, dicono: l'abbiamo fatto noi.", author: "Lao Tzu" },
  { quote: "La leadership efficace è mettere prima le persone.", author: "John Maxwell" },
  { quote: "Un leader si fa carico delle responsabilità, anche degli errori del team.", author: "Anonimo" },
  { quote: "La leadership non è dominare, ma servire.", author: "Anonimo" },
  { quote: "Un buon leader ispira, non comanda.", author: "Anonimo" },
  { quote: "La leadership è fare la cosa giusta, anche quando nessuno guarda.", author: "Anonimo" },
  { quote: "Un leader efficace sa ascoltare più di quanto parli.", author: "Anonimo" },
  { quote: "La responsabilità è il prezzo della grandezza.", author: "Winston Churchill" },
  { quote: "Un leader costruisce fiducia attraverso la coerenza.", author: "Anonimo" },
  { quote: "La leadership richiede coraggio di prendere decisioni difficili.", author: "Anonimo" },
  { quote: "Un vero leader non cerca il consenso, ma fa ciò che è giusto.", author: "Anonimo" },
  { quote: "La leadership è dare alle persone una piattaforma per diffondere idee.", author: "Seth Godin" },
  { quote: "Un leader forte sviluppa altri leader forti.", author: "Anonimo" },
  { quote: "La responsabilità non può essere delegata.", author: "Anonimo" },
  { quote: "Un leader guida con l'esempio, non con le parole.", author: "Anonimo" },
  { quote: "La leadership è avere una visione e la capacità di realizzarla.", author: "Anonimo" },
  { quote: "Un buon leader porta le persone dove vogliono andare. Un grande leader le porta dove non vogliono andare ma devono essere.", author: "Rosalynn Carter" },
  { quote: "La responsabilità inizia con la capacità di dire 'sono io il responsabile'.", author: "Anonimo" },
  { quote: "Un leader sa che il potere non è posseduto, è condiviso.", author: "Anonimo" },
  { quote: "La leadership è comunicare il valore e il potenziale delle persone in modo così chiaro che arrivino a vederlo in se stesse.", author: "Stephen Covey" },
  { quote: "Un leader efficace sa quando guidare e quando seguire.", author: "Anonimo" },
  { quote: "La responsabilità personale è il fondamento della leadership.", author: "Anonimo" },
  { quote: "Un leader non cerca scuse, cerca soluzioni.", author: "Anonimo" },
  { quote: "La leadership è l'arte di far fare a qualcuno qualcosa che tu vuoi perché lui lo vuole fare.", author: "Dwight D. Eisenhower" },
  { quote: "Un buon leader ammette i propri errori.", author: "Anonimo" },
  { quote: "La responsabilità è accettare le conseguenze delle proprie azioni.", author: "Anonimo" },
  { quote: "Un leader vede opportunità dove altri vedono problemi.", author: "Anonimo" },
  { quote: "La leadership richiede empatia e comprensione.", author: "Anonimo" },
  { quote: "Un vero leader celebra il successo del team, non il proprio.", author: "Anonimo" },
  { quote: "La responsabilità è l'obbligo di rispondere delle proprie azioni.", author: "Anonimo" },
  { quote: "Un leader ispira fiducia attraverso l'integrità.", author: "Anonimo" },
  { quote: "La leadership è servire, non essere serviti.", author: "Anonimo" },
  { quote: "Un buon leader delega compiti, non responsabilità.", author: "Anonimo" },
  { quote: "La responsabilità non ammette scuse.", author: "Anonimo" },
  { quote: "Un leader sa che ogni parola e azione conta.", author: "Anonimo" },
  { quote: "La leadership è dare potere agli altri, non esercitarlo su di loro.", author: "Anonimo" },
  { quote: "Un vero leader rimane calmo nella tempesta.", author: "Anonimo" },
  { quote: "La responsabilità inizia con piccole scelte quotidiane.", author: "Anonimo" },
  { quote: "Un leader efficace sa motivare senza manipolare.", author: "Anonimo" },
  { quote: "La leadership è trasformare una visione in realtà.", author: "Anonimo" },
  { quote: "Un buon leader sa quando è il momento di cambiare direzione.", author: "Anonimo" },
  { quote: "La responsabilità è il prezzo della libertà.", author: "Anonimo" },
  { quote: "Un leader non evita i conflitti, li gestisce costruttivamente.", author: "Anonimo" },
  { quote: "La leadership richiede coraggio morale.", author: "Anonimo" },
  { quote: "Un vero leader mette l'interesse del team prima del proprio.", author: "Anonimo" },
  { quote: "La responsabilità è essere affidabili in ogni circostanza.", author: "Anonimo" },
  { quote: "Un leader sa che il successo del team è il suo successo.", author: "Anonimo" },
  { quote: "La leadership è influenzare positivamente gli altri.", author: "Anonimo" },
  { quote: "Un buon leader sa quando dire no.", author: "Anonimo" },
  { quote: "La responsabilità è mantenere le promesse.", author: "Anonimo" },
  { quote: "Un leader efficace comunica chiaramente e ascolta attentamente.", author: "Anonimo" },
  { quote: "La leadership è creare un ambiente dove le persone possono dare il meglio.", author: "Anonimo" },
  { quote: "Un vero leader non cerca il riflettore, lo punta sui membri del team.", author: "Anonimo" },
  { quote: "La responsabilità è riconoscere il proprio ruolo in ogni risultato.", author: "Anonimo" },
  { quote: "Un leader sa che il potere deriva dal servizio, non dal controllo.", author: "Anonimo" },
  { quote: "La leadership è dare l'esempio in ogni momento.", author: "Anonimo" },
  { quote: "Un buon leader investe nello sviluppo delle persone.", author: "Anonimo" },
  { quote: "La responsabilità è essere proattivi, non reattivi.", author: "Anonimo" },
  { quote: "Un leader efficace sa bilanciare fermezza e compassione.", author: "Anonimo" },
  { quote: "La leadership è creare una cultura di eccellenza.", author: "Anonimo" },
  { quote: "Un vero leader non ha paura di circondare se stesso di persone migliori.", author: "Anonimo" },
  { quote: "La responsabilità è essere padroni del proprio destino.", author: "Anonimo" },
  { quote: "Un leader sa che l'umiltà è forza, non debolezza.", author: "Anonimo" },
  { quote: "La leadership è allineare le persone verso un obiettivo comune.", author: "Anonimo" },
  { quote: "Un buon leader riconosce e celebra i contributi di tutti.", author: "Anonimo" },
  { quote: "La responsabilità è rispondere delle proprie azioni senza cercare capri espiatori.", author: "Anonimo" },
  { quote: "Un leader efficace sa trasformare gli ostacoli in opportunità.", author: "Anonimo" },
  { quote: "La leadership è creare fiducia attraverso la trasparenza.", author: "Anonimo" },
  { quote: "Un vero leader non chiede rispetto, lo guadagna.", author: "Anonimo" },
  { quote: "La responsabilità è fare ciò che si dice di fare.", author: "Anonimo" },
  { quote: "Un leader sa che la diversità è un punto di forza.", author: "Anonimo" },
  { quote: "La leadership è ispirare gli altri a credere in se stessi.", author: "Anonimo" },
  { quote: "Un buon leader sa quando delegare e quando intervenire.", author: "Anonimo" },
  { quote: "La responsabilità è ammettere quando si ha torto.", author: "Anonimo" },
  { quote: "Un leader efficace sa che la comunicazione è bidirezionale.", author: "Anonimo" },
  { quote: "La leadership è creare significato nel lavoro quotidiano.", author: "Anonimo" },
  { quote: "Un vero leader aiuta gli altri a scoprire il proprio potenziale.", author: "Anonimo" },
  { quote: "La responsabilità è essere accountable per i risultati.", author: "Anonimo" },
  { quote: "Un leader sa che il cambiamento inizia da se stesso.", author: "Anonimo" },
  { quote: "La leadership è dare feedback costruttivo con empatia.", author: "Anonimo" },
  { quote: "Un buon leader sa che l'etica non è negoziabile.", author: "Anonimo" },
  { quote: "La responsabilità è agire con integrità in ogni situazione.", author: "Anonimo" },
  { quote: "Un leader efficace sa bilanciare visione a lungo termine e azione immediata.", author: "Anonimo" },
  { quote: "La leadership è creare una cultura dove l'errore è apprendimento.", author: "Anonimo" },
  { quote: "Un vero leader non cerca la perfezione, cerca il miglioramento continuo.", author: "Anonimo" },
  { quote: "La responsabilità è essere il cambiamento che vuoi vedere.", author: "Mahatma Gandhi" },

  // ── PERSEVERANZA E RESILIENZA (100 citazioni) ──────────────────────────────
  { quote: "Il segreto per andare avanti è iniziare.", author: "Mark Twain" },
  { quote: "Tutto quello che hai sempre voluto è dall'altra parte della paura.", author: "George Addair" },
  { quote: "La vita è per il 10% cosa ti accade e per il 90% come reagisci.", author: "Charles R. Swindoll" },
  { quote: "La pazienza è amara, ma il suo frutto è dolce.", author: "Aristotele" },
  { quote: "Il momento migliore per piantare un albero era vent'anni fa. Il secondo momento migliore è adesso.", author: "Proverbio cinese" },
  { quote: "Quando tutto sembra andare contro di te, ricorda che l'aereo decolla contro vento, non con il vento.", author: "Henry Ford" },
  { quote: "Le difficoltà spesso preparano le persone ordinarie a destini straordinari.", author: "C.S. Lewis" },
  { quote: "Non contare i giorni, fai in modo che i giorni contino.", author: "Muhammad Ali" },
  { quote: "La perseveranza è fallire 19 volte e avere successo la ventesima.", author: "Julie Andrews" },
  { quote: "Ciò che non mi uccide mi rende più forte.", author: "Friedrich Nietzsche" },
  { quote: "La resilienza non è ciò che ti accade, ma come rispondi a ciò che ti accade.", author: "Anonimo" },
  { quote: "Le tempeste rendono gli alberi più forti.", author: "Proverbio" },
  { quote: "La perseveranza è la chiave del successo in ogni impresa.", author: "Anonimo" },
  { quote: "Non arrenderti mai, i grandi risultati richiedono tempo.", author: "Anonimo" },
  { quote: "La resilienza è la capacità di riprendersi dalle avversità.", author: "Anonimo" },
  { quote: "Chi resiste vince.", author: "Proverbio" },
  { quote: "La perseveranza trasforma gli ostacoli in trampolini di lancio.", author: "Anonimo" },
  { quote: "Non è la specie più forte che sopravvive, ma quella più adattabile al cambiamento.", author: "Charles Darwin" },
  { quote: "La resilienza si costruisce affrontando le difficoltà, non evitandole.", author: "Anonimo" },
  { quote: "Ogni fallimento è un passo verso il successo.", author: "Anonimo" },
  { quote: "La perseveranza vince dove la forza fallisce.", author: "Anonimo" },
  { quote: "La resilienza è vedere le difficoltà come opportunità di crescita.", author: "Anonimo" },
  { quote: "Chi non si arrende, non può perdere.", author: "Anonimo" },
  { quote: "La perseveranza è continuare quando hai voglia di arrenderti.", author: "Anonimo" },
  { quote: "La resilienza è ritrovare equilibrio dopo ogni tempesta.", author: "Anonimo" },
  { quote: "I vincitori non si arrendono mai, chi si arrende non vince mai.", author: "Vince Lombardi" },
  { quote: "La perseveranza è la virtù dei forti.", author: "Anonimo" },
  { quote: "La resilienza si misura non da quanto cadi, ma da quanto velocemente ti rialzi.", author: "Anonimo" },
  { quote: "Ogni giorno è una nuova opportunità per ricominciare.", author: "Anonimo" },
  { quote: "La perseveranza è fede in azione.", author: "Anonimo" },
  { quote: "La resilienza non significa non cadere, significa rialzarsi ogni volta.", author: "Anonimo" },
  { quote: "Chi persevera, raggiunge.", author: "Proverbio" },
  { quote: "La perseveranza è pazienza in azione.", author: "Anonimo" },
  { quote: "La resilienza è speranza che non si spegne mai.", author: "Anonimo" },
  { quote: "Il vero coraggio è continuare quando vorresti mollare.", author: "Anonimo" },
  { quote: "La perseveranza è l'arte di non arrendersi mai.", author: "Anonimo" },
  { quote: "La resilienza è forza interiore che emerge nelle difficoltà.", author: "Anonimo" },
  { quote: "Chi cade sette volte, si rialza otto.", author: "Proverbio giapponese" },
  { quote: "La perseveranza è determinazione che dura nel tempo.", author: "Anonimo" },
  { quote: "La resilienza è elasticità dell'anima.", author: "Anonimo" },
  { quote: "Non importa quanto lentamente vai, purché non ti fermi.", author: "Confucio" },
  { quote: "La perseveranza è costanza nel perseguire un obiettivo.", author: "Anonimo" },
  { quote: "La resilienza è capacità di adattamento.", author: "Anonimo" },
  { quote: "Ogni ostacolo è un'opportunità mascherata.", author: "Anonimo" },
  { quote: "La perseveranza è tenacia che non conosce resa.", author: "Anonimo" },
  { quote: "La resilienza è ottimismo radicato nella realtà.", author: "Anonimo" },
  { quote: "Chi si arrende troppo presto, non saprà mai quanto era vicino al successo.", author: "Anonimo" },
  { quote: "La perseveranza è volontà che non si piega.", author: "Anonimo" },
  { quote: "La resilienza è saggezza che nasce dalle difficoltà.", author: "Anonimo" },
  { quote: "Le sfide sono ciò che rendono la vita interessante.", author: "Anonimo" },
  { quote: "La perseveranza è fiducia in se stessi.", author: "Anonimo" },
  { quote: "La resilienza è coraggio che si rinnova ogni giorno.", author: "Anonimo" },
  { quote: "Chi non rischia non rosica.", author: "Proverbio" },
  { quote: "La perseveranza è disciplina applicata nel tempo.", author: "Anonimo" },
  { quote: "La resilienza è flessibilità senza perdere i propri valori.", author: "Anonimo" },
  { quote: "Ogni fine è un nuovo inizio.", author: "Anonimo" },
  { quote: "La perseveranza è la madre del successo.", author: "Anonimo" },
  { quote: "La resilienza è arte di trasformare le ferite in saggezza.", author: "Anonimo" },
  { quote: "Chi insiste, vince.", author: "Proverbio" },
  { quote: "La perseveranza è resistenza costruttiva.", author: "Anonimo" },
  { quote: "La resilienza è capacità di trovare senso nelle difficoltà.", author: "Anonimo" },
  { quote: "Dopo la tempesta viene il sereno.", author: "Proverbio" },
  { quote: "La perseveranza è speranza attiva.", author: "Anonimo" },
  { quote: "La resilienza è equilibrio tra accettazione e cambiamento.", author: "Anonimo" },
  { quote: "Chi non molla, non perde.", author: "Anonimo" },
  { quote: "La perseveranza è impegno costante.", author: "Anonimo" },
  { quote: "La resilienza è capacità di reinventarsi.", author: "Anonimo" },
  { quote: "Ogni battuta d'arresto è un setup per un comeback.", author: "Anonimo" },
  { quote: "La perseveranza è fedeltà ai propri obiettivi.", author: "Anonimo" },
  { quote: "La resilienza è crescere attraverso le difficoltà, non solo superarle.", author: "Anonimo" },
  { quote: "Chi resiste, conquista.", author: "Proverbio" },
  { quote: "La perseveranza è continuare quando gli altri si fermano.", author: "Anonimo" },
  { quote: "La resilienza è forza che si scopre solo nelle avversità.", author: "Anonimo" },
  { quote: "Non esiste vento favorevole per il marinaio che non sa dove andare.", author: "Seneca" },
  { quote: "La perseveranza è pazienza armata di determinazione.", author: "Anonimo" },
  { quote: "La resilienza è ricostruire dopo ogni tempesta.", author: "Anonimo" },
  { quote: "Chi semina con costanza, raccoglie con abbondanza.", author: "Proverbio" },
  { quote: "La perseveranza è credere quando sembra impossibile.", author: "Anonimo" },
  { quote: "La resilienza è trasformare i problemi in possibilità.", author: "Anonimo" },
  { quote: "L'albero più forte non è quello che non ha mai conosciuto il vento.", author: "Anonimo" },
  { quote: "La perseveranza è l'ultima chiave che apre ogni porta.", author: "Anonimo" },
  { quote: "La resilienza è imparare a ballare sotto la pioggia.", author: "Anonimo" },
  { quote: "Chi non si ferma, prima o poi arriva.", author: "Proverbio" },
  { quote: "La perseveranza è andare avanti un passo alla volta.", author: "Anonimo" },
  { quote: "La resilienza è rinascere dalle proprie ceneri.", author: "Anonimo" },
  { quote: "Il diamante è carbone che ha resistito alla pressione.", author: "Anonimo" },
  { quote: "La perseveranza è non accettare il no come risposta finale.", author: "Anonimo" },
  { quote: "La resilienza è vedere l'arcobaleno dopo la tempesta.", author: "Anonimo" },
  { quote: "Chi non abbandona la barca, prima o poi arriva a riva.", author: "Proverbio" },
  { quote: "La perseveranza è tenere gli occhi sulla meta nonostante gli ostacoli.", author: "Anonimo" },
  { quote: "La resilienza è scegliere di sorridere nonostante le lacrime.", author: "Anonimo" },
  { quote: "Dopo la notte più buia, sorge sempre il sole.", author: "Anonimo" },
  { quote: "La perseveranza è il carburante del successo.", author: "Anonimo" },
  { quote: "La resilienza è saper perdere battaglie per vincere la guerra.", author: "Anonimo" },
  { quote: "Chi continua a camminare, prima o poi esce dal deserto.", author: "Proverbio" },
  { quote: "La perseveranza è l'arma dei vincenti.", author: "Anonimo" },

  // ── INNOVAZIONE E CREATIVITÀ (100 citazioni) ───────────────────────────────
  { quote: "L'innovazione distingue un leader da un follower.", author: "Steve Jobs" },
  { quote: "La creatività è l'intelligenza che si diverte.", author: "Albert Einstein" },
  { quote: "Non si può scoprire nuovi oceani se non si ha il coraggio di perdere di vista la riva.", author: "André Gide" },
  { quote: "L'immaginazione è più importante della conoscenza.", author: "Albert Einstein" },
  { quote: "Le idee migliori vengono da chi non ha paura di sbagliare.", author: "Anonimo" },
  { quote: "L'innovazione è vedere ciò che tutti vedono e pensare ciò che nessuno ha pensato.", author: "Albert Szent-Györgyi" },
  { quote: "La creatività richiede il coraggio di lasciare andare le certezze.", author: "Erich Fromm" },
  { quote: "Ogni artista è stato prima un dilettante.", author: "Ralph Waldo Emerson" },
  { quote: "L'innovazione non è mai stata il risultato del pensiero logico.", author: "Albert Einstein" },
  { quote: "La creatività è contagiosa, trasmettetela.", author: "Albert Einstein" },
  { quote: "Il modo migliore per avere una buona idea è avere tante idee.", author: "Linus Pauling" },
  { quote: "L'innovazione è fallire in avanti.", author: "Anonimo" },
  { quote: "La creatività non si esaurisce, più la usi più ne hai.", author: "Maya Angelou" },
  { quote: "Le persone creative sono curiose, flessibili, persistenti e indipendenti.", author: "Henri Matisse" },
  { quote: "L'innovazione è trasformare l'impossibile in possibile.", author: "Anonimo" },
  { quote: "La creatività è permettersi di fare errori. L'arte è sapere quali tenere.", author: "Scott Adams" },
  { quote: "Ogni atto di creazione è prima di tutto un atto di distruzione.", author: "Pablo Picasso" },
  { quote: "L'innovazione è ciò che distingue un capo da un leader.", author: "Steve Jobs" },
  { quote: "La creatività è vedere connessioni dove altri vedono solo casualità.", author: "Anonimo" },
  { quote: "Il pensiero creativo non è un talento, è un'abilità che può essere imparata.", author: "Edward de Bono" },
  { quote: "L'innovazione è l'applicazione pratica della creatività.", author: "Anonimo" },
  { quote: "La creatività è la capacità di vedere l'ordinario in modo straordinario.", author: "Anonimo" },
  { quote: "Le grandi idee spesso arrivano nei momenti di ozio creativo.", author: "Anonimo" },
  { quote: "L'innovazione è rischiare il ridicolo per cambiare lo status quo.", author: "Anonimo" },
  { quote: "La creatività richiede il coraggio di essere diversi.", author: "Anonimo" },
  { quote: "Non copiare, crea.", author: "Anonimo" },
  { quote: "L'innovazione è combinare idee esistenti in modi nuovi.", author: "Anonimo" },
  { quote: "La creatività è l'arte di connettere i puntini.", author: "Steve Jobs" },
  { quote: "Le menti creative prosperano nel caos.", author: "Anonimo" },
  { quote: "L'innovazione inizia con una domanda: 'E se...?'", author: "Anonimo" },
  { quote: "La creatività non conosce regole, solo possibilità.", author: "Anonimo" },
  { quote: "Pensa fuori dagli schemi.", author: "Proverbio" },
  { quote: "L'innovazione è vedere opportunità dove altri vedono problemi.", author: "Anonimo" },
  { quote: "La creatività è il potere di connettere il non connesso.", author: "William Plomer" },
  { quote: "Le idee rivoluzionarie spesso sembrano assurde all'inizio.", author: "Anonimo" },
  { quote: "L'innovazione è il motore del progresso.", author: "Anonimo" },
  { quote: "La creatività è il coraggio di esplorare l'ignoto.", author: "Anonimo" },
  { quote: "Chi non innova, ristagna.", author: "Anonimo" },
  { quote: "L'innovazione è disturbare lo status quo con uno scopo.", author: "Anonimo" },
  { quote: "La creatività è vedere ciò che non c'è ancora.", author: "Anonimo" },
  { quote: "Le migliori idee nascono dall'incrocio di discipline diverse.", author: "Anonimo" },
  { quote: "L'innovazione è portare il futuro nel presente.", author: "Anonimo" },
  { quote: "La creatività è il linguaggio dell'anima.", author: "Anonimo" },
  { quote: "Chi non sperimenta, non innova.", author: "Anonimo" },
  { quote: "L'innovazione è audacia guidata dall'intuizione.", author: "Anonimo" },
  { quote: "La creatività è libertà di espressione.", author: "Anonimo" },
  { quote: "Le idee folli di oggi sono le innovazioni di domani.", author: "Anonimo" },
  { quote: "L'innovazione richiede tolleranza al fallimento.", author: "Anonimo" },
  { quote: "La creatività è la capacità di generare novità.", author: "Anonimo" },
  { quote: "Ogni grande innovazione inizia con un sogno.", author: "Anonimo" },
  { quote: "L'innovazione è risolvere problemi in modi inaspettati.", author: "Anonimo" },
  { quote: "La creatività è l'energia dell'evoluzione.", author: "Anonimo" },
  { quote: "Chi osa, innova.", author: "Anonimo" },
  { quote: "L'innovazione è trasformare idee in valore.", author: "Anonimo" },
  { quote: "La creatività è vedere possibilità infinite.", author: "Anonimo" },
  { quote: "Le grandi innovazioni spesso nascono da piccole osservazioni.", author: "Anonimo" },
  { quote: "L'innovazione è il coraggio di essere i primi.", author: "Anonimo" },
  { quote: "La creatività è giocare con le idee.", author: "Anonimo" },
  { quote: "Chi innova, guida il cambiamento.", author: "Anonimo" },
  { quote: "L'innovazione è pensare l'impensabile e farlo.", author: "Anonimo" },
  { quote: "La creatività è l'antidoto alla routine.", author: "Anonimo" },
  { quote: "Le idee non hanno valore finché non vengono implementate.", author: "Anonimo" },
  { quote: "L'innovazione è sfidare l'ovvio.", author: "Anonimo" },
  { quote: "La creatività è vedere il mondo con occhi nuovi ogni giorno.", author: "Anonimo" },
  { quote: "Chi non rischia di sbagliare, non innova.", author: "Anonimo" },
  { quote: "L'innovazione è creare ciò che ancora non esiste.", author: "Anonimo" },
  { quote: "La creatività è la capacità di improvvisare.", author: "Anonimo" },
  { quote: "Le innovazioni dirompenti cambiano le regole del gioco.", author: "Anonimo" },
  { quote: "L'innovazione è rendere semplice il complesso.", author: "Anonimo" },
  { quote: "La creatività è l'arte di combinare elementi in modi inaspettati.", author: "Anonimo" },
  { quote: "Chi pensa diversamente, innova.", author: "Anonimo" },
  { quote: "L'innovazione è trasformare limiti in opportunità.", author: "Anonimo" },
  { quote: "La creatività è vedere connessioni nascoste.", author: "Anonimo" },
  { quote: "Le grandi innovazioni partono da domande semplici.", author: "Anonimo" },
  { quote: "L'innovazione è il risultato di curiosità applicata.", author: "Anonimo" },
  { quote: "La creatività è pensiero laterale.", author: "Edward de Bono" },
  { quote: "Chi immagina, può innovare.", author: "Anonimo" },
  { quote: "L'innovazione è osare dove altri esitano.", author: "Anonimo" },
  { quote: "La creatività è l'essenza dell'umanità.", author: "Anonimo" },
  { quote: "Le innovazioni nascono dall'intersezione di idee diverse.", author: "Anonimo" },
  { quote: "L'innovazione è vedere il futuro prima che arrivi.", author: "Anonimo" },
  { quote: "La creatività è improvvisazione controllata.", author: "Anonimo" },
  { quote: "Chi esplora, scopre e innova.", author: "Anonimo" },
  { quote: "L'innovazione è trasformare l'ordinario in straordinario.", author: "Anonimo" },
  { quote: "La creatività è la scintilla che accende il cambiamento.", author: "Anonimo" },
  { quote: "Le idee migliori spesso vengono dalle persone più inaspettate.", author: "Anonimo" },
  { quote: "L'innovazione è progresso intenzionale.", author: "Anonimo" },
  { quote: "La creatività è l'abilità di vedere ciò che tutti guardano ma nessuno vede.", author: "Anonimo" },
  { quote: "Chi sfida le convenzioni, innova.", author: "Anonimo" },
  { quote: "L'innovazione è rendere reale l'immaginario.", author: "Anonimo" },
  { quote: "La creatività è pensare senza confini.", author: "Anonimo" },
  { quote: "Le innovazioni radicali richiedono pensiero radicale.", author: "Anonimo" },
  { quote: "L'innovazione è il coraggio di essere diversi.", author: "Anonimo" },
  { quote: "La creatività è l'origine di ogni progresso.", author: "Anonimo" },

  // ── SAGGEZZA E RIFLESSIONE (100 citazioni) ─────────────────────────────────
  { quote: "Conosci te stesso.", author: "Socrate" },
  { quote: "La semplicità è l'ultima sofisticazione.", author: "Leonardo da Vinci" },
  { quote: "Chi controlla gli altri può essere potente, ma chi controlla se stesso è ancora più potente.", author: "Lao Tzu" },
  { quote: "Il saggio sa di non sapere.", author: "Socrate" },
  { quote: "La vita è ciò che accade mentre sei impegnato a fare altri piani.", author: "John Lennon" },
  { quote: "Non è ricco chi ha molto, ma chi ha bisogno di poco.", author: "Epitteto" },
  { quote: "Il tempo è la cosa più preziosa che un uomo possa spendere.", author: "Teofrasto" },
  { quote: "La felicità non è avere ciò che desideri, ma desiderare ciò che hai.", author: "Anonimo" },
  { quote: "Chi parla semina, chi tace raccoglie.", author: "Proverbio" },
  { quote: "La saggezza è sapere cosa fare, la virtù è farlo.", author: "David Starr Jordan" },
  { quote: "Non tutto ciò che può essere contato conta, e non tutto ciò che conta può essere contato.", author: "Albert Einstein" },
  { quote: "Il silenzio è il più grande insegnante.", author: "Anonimo" },
  { quote: "Chi sa ascoltare, non solo capisce le parole, ma anche i silenzi.", author: "Anonimo" },
  { quote: "La saggezza inizia nella meraviglia.", author: "Socrate" },
  { quote: "Il viaggio è la ricompensa.", author: "Proverbio cinese" },
  { quote: "Non è quanto hai, ma quanto godi che ti rende felice.", author: "Charles Spurgeon" },
  { quote: "Chi pianta un seme di gentilezza, raccoglie un bouquet di felicità.", author: "Proverbio" },
  { quote: "La saggezza non si eredita, si impara.", author: "Anonimo" },
  { quote: "Il tempo guarisce tutte le ferite.", author: "Proverbio" },
  { quote: "Non giudicare un libro dalla copertina.", author: "Proverbio" },
  { quote: "La saggezza è l'arte di vivere.", author: "Plutarco" },
  { quote: "Chi semina vento, raccoglie tempesta.", author: "Proverbio" },
  { quote: "Non puoi fermare le onde, ma puoi imparare a surfare.", author: "Jon Kabat-Zinn" },
  { quote: "La saggezza è la sintesi di conoscenza ed esperienza.", author: "Anonimo" },
  { quote: "L'esperienza è il miglior insegnante.", author: "Proverbio" },
  { quote: "Chi troppo vuole, nulla stringe.", author: "Proverbio" },
  { quote: "La saggezza è sapere quando parlare e quando tacere.", author: "Anonimo" },
  { quote: "Il presente è un dono, per questo si chiama presente.", author: "Bil Keane" },
  { quote: "Chi ha fretta, sbaglia.", author: "Proverbio" },
  { quote: "La saggezza è vedere le cose come sono, non come vorremmo che fossero.", author: "Anonimo" },
  { quote: "Ogni cosa a suo tempo.", author: "Proverbio" },
  { quote: "Non c'è vento favorevole per chi non sa dove andare.", author: "Seneca" },
  { quote: "La saggezza è equilibrio tra mente e cuore.", author: "Anonimo" },
  { quote: "Chi dorme non piglia pesci.", author: "Proverbio" },
  { quote: "Il miglior momento per piantare un albero era vent'anni fa. Il secondo miglior momento è ora.", author: "Proverbio cinese" },
  { quote: "La saggezza è accettare ciò che non si può cambiare.", author: "Anonimo" },
  { quote: "L'erba del vicino è sempre più verde.", author: "Proverbio" },
  { quote: "Chi ben comincia è a metà dell'opera.", author: "Proverbio" },
  { quote: "La saggezza è riconoscere i propri limiti.", author: "Anonimo" },
  { quote: "Chi va piano va sano e va lontano.", author: "Proverbio" },
  { quote: "Le parole volano, gli scritti rimangono.", author: "Proverbio latino" },
  { quote: "La saggezza è l'arte del discernimento.", author: "Anonimo" },
  { quote: "Chi tace acconsente.", author: "Proverbio" },
  { quote: "Meglio prevenire che curare.", author: "Proverbio" },
  { quote: "La saggezza è vedere il tutto, non solo le parti.", author: "Anonimo" },
  { quote: "Chi fa da sé, fa per tre.", author: "Proverbio" },
  { quote: "L'occasione fa l'uomo ladro.", author: "Proverbio" },
  { quote: "La saggezza è pazienza applicata.", author: "Anonimo" },
  { quote: "Chi non risica, non rosica.", author: "Proverbio" },
  { quote: "Non tutto il mal vien per nuocere.", author: "Proverbio" },
  { quote: "La saggezza è umiltà consapevole.", author: "Anonimo" },
  { quote: "Chi di spada ferisce, di spada perisce.", author: "Proverbio" },
  { quote: "Meglio tardi che mai.", author: "Proverbio" },
  { quote: "La saggezza è la capacità di imparare da ogni esperienza.", author: "Anonimo" },
  { quote: "A caval donato non si guarda in bocca.", author: "Proverbio" },
  { quote: "Chi la dura la vince.", author: "Proverbio" },
  { quote: "La saggezza è vedere le conseguenze prima di agire.", author: "Anonimo" },
  { quote: "Tra il dire e il fare c'è di mezzo il mare.", author: "Proverbio" },
  { quote: "Non è tutto oro quel che luccica.", author: "Proverbio" },
  { quote: "La saggezza è saper scegliere le proprie battaglie.", author: "Anonimo" },
  { quote: "Chi trova un amico, trova un tesoro.", author: "Proverbio" },
  { quote: "L'unione fa la forza.", author: "Proverbio" },
  { quote: "La saggezza è riconoscere il valore del tempo.", author: "Anonimo" },
  { quote: "Chi rompe paga.", author: "Proverbio" },
  { quote: "Meglio un uovo oggi che una gallina domani.", author: "Proverbio" },
  { quote: "La saggezza è l'equilibrio tra pensiero e azione.", author: "Anonimo" },
  { quote: "Chi semina raccoglie.", author: "Proverbio" },
  { quote: "Il buongiorno si vede dal mattino.", author: "Proverbio" },
  { quote: "La saggezza è vedere oltre l'apparenza.", author: "Anonimo" },
  { quote: "Chi dorme non prende pesci.", author: "Proverbio" },
  { quote: "L'abito non fa il monaco.", author: "Proverbio" },
  { quote: "La saggezza è accettare l'incertezza della vita.", author: "Anonimo" },
  { quote: "Chi lascia la via vecchia per la nuova, sa quel che lascia ma non sa quel che trova.", author: "Proverbio" },
  { quote: "Paese che vai, usanza che trovi.", author: "Proverbio" },
  { quote: "La saggezza è sapere quando chiedere aiuto.", author: "Anonimo" },
  { quote: "Chi va con lo zoppo impara a zoppicare.", author: "Proverbio" },
  { quote: "Il tempo è denaro.", author: "Benjamin Franklin" },
  { quote: "La saggezza è la capacità di adattarsi.", author: "Anonimo" },
  { quote: "Chi si accontenta gode.", author: "Proverbio" },
  { quote: "Dove c'è fumo, c'è fuoco.", author: "Proverbio" },
  { quote: "La saggezza è vedere l'opportunità nel problema.", author: "Anonimo" },
  { quote: "Chi nasce tondo non muore quadrato.", author: "Proverbio" },
  { quote: "Il lupo perde il pelo ma non il vizio.", author: "Proverbio" },
  { quote: "La saggezza è riconoscere i propri errori.", author: "Anonimo" },
  { quote: "Chi ben fa, ben aspetta.", author: "Proverbio" },
  { quote: "A buon intenditor poche parole.", author: "Proverbio" },
  { quote: "La saggezza è la sintesi di esperienza e riflessione.", author: "Anonimo" },
  { quote: "Chi non sa tacere, non sa neppure parlare.", author: "Proverbio" },
  { quote: "Il silenzio è d'oro.", author: "Proverbio" },
  { quote: "La saggezza è sapere quando fermarsi.", author: "Anonimo" },
  { quote: "Chi la fa, l'aspetti.", author: "Proverbio" },
  { quote: "Non vendere la pelle dell'orso prima di averlo ucciso.", author: "Proverbio" },
  { quote: "La saggezza è l'arte di vivere in armonia.", author: "Anonimo" },
  { quote: "Chi semina vento raccoglie tempesta.", author: "Proverbio" },

  // ── MOTIVAZIONE E ISPIRAZIONE (106 citazioni) ──────────────────────────────
  { quote: "Sii il cambiamento che vuoi vedere nel mondo.", author: "Mahatma Gandhi" },
  { quote: "La vita è troppo breve per essere piccola.", author: "Benjamin Disraeli" },
  { quote: "Fai della tua vita un sogno e di un sogno una realtà.", author: "Antoine de Saint-Exupéry" },
  { quote: "L'unica persona che sei destinato a diventare è la persona che decidi di essere.", author: "Ralph Waldo Emerson" },
  { quote: "Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.", author: "Eleanor Roosevelt" },
  { quote: "Non aspettare il momento perfetto, prendi il momento e rendilo perfetto.", author: "Anonimo" },
  { quote: "La tua vita è il risultato delle tue scelte.", author: "Anonimo" },
  { quote: "Credi in te stesso e sarai inarrestabile.", author: "Anonimo" },
  { quote: "Il segreto per andare avanti è cominciare.", author: "Mark Twain" },
  { quote: "Non puoi cambiare il passato, ma puoi costruire il futuro.", author: "Anonimo" },
  { quote: "Ogni grande viaggio inizia con un piccolo passo.", author: "Lao Tzu" },
  { quote: "La motivazione ti fa iniziare, l'abitudine ti fa continuare.", author: "Jim Ryun" },
  { quote: "Se puoi sognarlo, puoi farlo.", author: "Walt Disney" },
  { quote: "Il momento migliore per agire è adesso.", author: "Anonimo" },
  { quote: "Non limitare le tue sfide, sfida i tuoi limiti.", author: "Anonimo" },
  { quote: "La vita inizia dove finisce la tua zona di comfort.", author: "Neale Donald Walsch" },
  { quote: "Sei più forte di quanto pensi.", author: "Anonimo" },
  { quote: "Non arrenderti mai, i miracoli accadono ogni giorno.", author: "Anonimo" },
  { quote: "Il tuo unico limite sei tu stesso.", author: "Anonimo" },
  { quote: "Fai oggi ciò che altri non faranno, così domani potrai fare ciò che altri non possono.", author: "Anonimo" },
  { quote: "La differenza tra sogno e obiettivo è una data.", author: "Harvey MacKay" },
  { quote: "Non smettere quando sei stanco, smetti quando hai finito.", author: "Anonimo" },
  { quote: "Il dolore è temporaneo, l'orgoglio è per sempre.", author: "Anonimo" },
  { quote: "Ogni giorno è una nuova opportunità per brillare.", author: "Anonimo" },
  { quote: "La vita è un'avventura, osa viverla.", author: "Madre Teresa" },
  { quote: "Non aspettare che le cose accadano, fai in modo che accadano.", author: "Anonimo" },
  { quote: "Il successo è un viaggio, non una destinazione.", author: "Ben Sweetland" },
  { quote: "Se non insegui ciò che vuoi, non lo avrai mai.", author: "Anonimo" },
  { quote: "La tua vita può cambiare in un istante, inizia adesso.", author: "Anonimo" },
  { quote: "Non contare i giorni, fai in modo che i giorni contino.", author: "Muhammad Ali" },
  { quote: "Scegli di essere ottimista, fa sentire meglio.", author: "Dalai Lama" },
  { quote: "La vita è 10% ciò che ti accade e 90% come reagisci.", author: "Charles R. Swindoll" },
  { quote: "Fai qualcosa oggi che il tuo futuro te stesso ti ringrazierà.", author: "Anonimo" },
  { quote: "Non c'è ascensore per il successo, devi prendere le scale.", author: "Zig Ziglar" },
  { quote: "Il meglio deve ancora venire.", author: "Anonimo" },
  { quote: "La vita è troppo importante per essere presa sul serio.", author: "Oscar Wilde" },
  { quote: "Credi che puoi e sei già a metà strada.", author: "Theodore Roosevelt" },
  { quote: "Il tuo tempo è limitato, quindi non sprecarlo vivendo la vita di qualcun altro.", author: "Steve Jobs" },
  { quote: "Non esiste il momento perfetto, esiste solo il momento presente.", author: "Anonimo" },
  { quote: "La felicità è una scelta, non un risultato.", author: "Ralph Marston" },
  { quote: "Fai della tua vita un capolavoro.", author: "Leonardo da Vinci" },
  { quote: "Il coraggio è resistenza alla paura, controllo della paura, non assenza di paura.", author: "Mark Twain" },
  { quote: "Non rimpiangere, ogni esperienza ti ha reso ciò che sei.", author: "Anonimo" },
  { quote: "La vita è bella, godila.", author: "Anonimo" },
  { quote: "Non cercare la felicità, creala.", author: "Anonimo" },
  { quote: "Il segreto della felicità è la libertà, e il segreto della libertà è il coraggio.", author: "Tucidide" },
  { quote: "Vivi come se dovessi morire domani, impara come se dovessi vivere per sempre.", author: "Mahatma Gandhi" },
  { quote: "La vita è un dono, ecco perché si chiama presente.", author: "Anonimo" },
  { quote: "Non puoi controllare tutto, ma puoi controllare la tua attitudine.", author: "Anonimo" },
  { quote: "Il miglior modo per prevedere il futuro è crearlo.", author: "Peter Drucker" },
  { quote: "Sii te stesso, tutti gli altri sono già occupati.", author: "Oscar Wilde" },
  { quote: "Non smettere di sognare solo perché hai avuto un incubo.", author: "Anonimo" },
  { quote: "La vita è come andare in bicicletta: per mantenere l'equilibrio devi muoverti.", author: "Albert Einstein" },
  { quote: "Fai ciò che ami e non lavorerai un solo giorno della tua vita.", author: "Confucio" },
  { quote: "Il segreto del cambiamento è concentrare tutta l'energia non nel combattere il vecchio, ma nel costruire il nuovo.", author: "Socrate" },
  { quote: "Non esiste fallimento, solo feedback.", author: "Anonimo" },
  { quote: "La vita è una serie di scelte, scegli saggiamente.", author: "Anonimo" },
  { quote: "Ogni mattina nasce un nuovo giorno, rendilo straordinario.", author: "Anonimo" },
  { quote: "La motivazione è ciò che ti fa partire, l'abitudine è ciò che ti fa continuare.", author: "Jim Ryun" },
  { quote: "Non vivere la stessa anno 75 volte e chiamarla vita.", author: "Robin Sharma" },
  { quote: "La vita è come uno specchio, ti sorride se la guardi sorridendo.", author: "Anonimo" },
  { quote: "Il segreto per avere tutto è credere di averlo già.", author: "Anonimo" },
  { quote: "Non aspettare che la tempesta passi, impara a ballare sotto la pioggia.", author: "Anonimo" },
  { quote: "La vita è 1% cosa ti accade e 99% come reagisci.", author: "Anonimo" },
  { quote: "Sogna grandi sogni, poi falli diventare realtà.", author: "Anonimo" },
  { quote: "Non contare i minuti, fai in modo che i minuti contino.", author: "Anonimo" },
  { quote: "La vita è troppo breve per non fare ciò che ami.", author: "Anonimo" },
  { quote: "Sii il protagonista della tua vita, non uno spettatore.", author: "Anonimo" },
  { quote: "Il tuo potenziale è infinito.", author: "Anonimo" },
  { quote: "Non guardare indietro, non ci stai andando.", author: "Anonimo" },
  { quote: "La vita è un'avventura audace o niente.", author: "Helen Keller" },
  { quote: "Fai accadere le cose, non aspettare che accadano.", author: "Anonimo" },
  { quote: "Il meglio deve ancora venire, credici.", author: "Anonimo" },
  { quote: "Non accontentarti mai della mediocrità.", author: "Anonimo" },
  { quote: "La vita è fatta di piccoli momenti che diventano grandi ricordi.", author: "Anonimo" },
  { quote: "Sii grato per ciò che hai mentre lavori per ciò che vuoi.", author: "Anonimo" },
  { quote: "Il successo non è quanto in alto arrivi, ma quanto in alto rimbalzi quando tocchi il fondo.", author: "George S. Patton" },
  { quote: "Non lasciare che ciò che non puoi fare interferisca con ciò che puoi fare.", author: "John Wooden" },
  { quote: "La vita è una tela bianca, e devi gettare su di essa tutta la pittura che puoi.", author: "Danny Kaye" },
  { quote: "Fai della tua passione il tuo lavoro e non lavorerai mai un giorno nella tua vita.", author: "Anonimo" },
  { quote: "Il segreto per andare avanti è fare il primo passo.", author: "Anonimo" },
  { quote: "Non aspettare condizioni ideali, inizia da dove sei con quello che hai.", author: "Anonimo" },
  { quote: "La vita è troppo importante per essere vissuta a metà.", author: "Anonimo" },
  { quote: "Ogni giorno è una nuova pagina, scrivi una bella storia.", author: "Anonimo" },
  { quote: "Non essere prigioniero del tuo passato, sii l'architetto del tuo futuro.", author: "Anonimo" },
  { quote: "Il coraggio non è l'assenza di paura, ma la decisione che qualcos'altro è più importante della paura.", author: "Ambrose Redmoon" },
  { quote: "La vita è un'eco: ciò che invii, ritorna.", author: "Zig Ziglar" },
  { quote: "Non smettere mai di provare, non smettere mai di credere, non smettere mai di sognare.", author: "Anonimo" },
  { quote: "Il tuo atteggiamento determina la tua altitudine.", author: "Zig Ziglar" },
  { quote: "La vita non è una prova generale, è lo spettacolo.", author: "Anonimo" },
  { quote: "Fai delle tue giornate capolavori.", author: "John Wooden" },
  { quote: "Non guardare l'orologio, fai quello che fa: continua ad andare avanti.", author: "Sam Levenson" },
  { quote: "La vita è come una fotografia: ti serve il negativo per sviluppare.", author: "Anonimo" },
  { quote: "Sii la migliore versione di te stesso, non una copia di qualcun altro.", author: "Anonimo" },
  { quote: "Il viaggio di mille miglia inizia con un singolo passo.", author: "Lao Tzu" },
  { quote: "Non aspettare il treno perfetto, prendi quello che passa e rendilo perfetto.", author: "Anonimo" },
  { quote: "La vita è ciò che fai di essa, sempre stata, sempre sarà.", author: "Grandma Moses" },
  { quote: "Ogni giorno porta nuove possibilità, coglile.", author: "Anonimo" },
  { quote: "Non lasciare che le ombre di ieri oscurino il sole di domani.", author: "Anonimo" },
  { quote: "La felicità non è qualcosa di pronto. Viene dalle tue azioni.", author: "Dalai Lama" },
  { quote: "Vivi la vita che hai immaginato.", author: "Henry David Thoreau" },

]

/**
 * Composable per gestire la citazione del giorno
 * Supporta API esterna (quotes_api) con fallback locale
 * 
 * @param {string} apiUrl - URL base dell'API (opzionale)
 * @param {number|string} userId - ID utente per personalizzare la citazione (opzionale)
 * @returns {Object} { citazione, loading, errore, ricarica }
 */
export function useCitazioneDelGiorno(apiUrl = null, userId = null) {
  const citazione = ref({ quote: '', author: '' })
  const loading = ref(false)
  const errore = ref(null)

  /**
   * Seleziona una citazione locale casuale ma deterministica
   * Usa data + userId come seed per avere citazioni diverse per utente
   * ma stabili per tutta la giornata
   */
  function getCitazioneLocale() {
    const oggi = new Date().toISOString().split('T')[0] // YYYY-MM-DD
    // Combina data e userId per hash univoco per utente
    const seed = `${oggi}-${userId || 'default'}`
    
    // Algoritmo hash migliorato (FNV-1a variant) per ridurre collisioni
    let hash = 2166136261 // FNV offset basis
    for (let i = 0; i < seed.length; i++) {
      hash ^= seed.charCodeAt(i)
      hash += (hash << 1) + (hash << 4) + (hash << 7) + (hash << 8) + (hash << 24)
    }
    
    // Assicura che l'hash sia positivo e nel range
    const indice = Math.abs(hash >>> 0) % CITAZIONI_LOCALI.length
    return CITAZIONI_LOCALI[indice]
  }

  /**
   * Carica citazione dall'API esterna
   */
  async function caricaDaAPI() {
    if (!apiUrl) return null

    try {
      // Supporta sia URL base che URL completi
      let endpoint = apiUrl
      if (!apiUrl.includes('/api/randomquote')) {
        endpoint = `${apiUrl}/api/randomquote?language=it`
      }
      
      const response = await fetch(endpoint, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
        // Timeout di 5 secondi
        signal: AbortSignal.timeout(5000)
      })

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`)
      }

      const data = await response.json()
      
      // Verifica che abbiamo i campi necessari
      if (data.quote && data.author) {
        return {
          quote: data.quote,
          author: data.author
        }
      }
      
      return null
    } catch (err) {
      console.warn('Errore caricamento citazione da API:', err.message)
      return null
    }
  }

  /**
   * Carica la citazione (sempre personalizzata per userId)
   */
  async function carica() {
    loading.value = true
    errore.value = null

    try {
      // SEMPRE usa citazione locale personalizzata per userId
      citazione.value = getCitazioneLocale()
      
      // Opzionalmente, se vuoi più varietà, potresti mixare con API
      // ma mantenendo la personalizzazione locale come base
    } catch (err) {
      console.error('Errore caricamento citazione:', err)
      errore.value = err.message
      citazione.value = getCitazioneLocale()
    } finally {
      loading.value = false
    }
  }

  /**
   * Ricarica la citazione (forza nuovo fetch)
   */
  function ricarica() {
    carica()
  }

  // Carica automaticamente al mount
  onMounted(() => {
    carica()
  })

  return {
    citazione,
    loading,
    errore,
    ricarica
  }
}